import "server-only";
import { randomUUID } from "node:crypto";

/**
 * In-memory state for the local HP2 sandbox gateway.
 *
 * The sandbox is wire-compatible with the real HP2 Single-Pay API — same
 * request/response shapes, same HMAC verification, same webhook format — so
 * the rest of the codebase (HP2Client, webhook handler, UI) treats the
 * sandbox identically to live HP2. The only difference: the "HP2 server"
 * is this app's own Next.js routes under `/sandbox/hp2-gateway/*`.
 *
 * This lets us demo the full flow (create link → customer pays → webhook
 * fires → on-chain CreditLine.onSaleReceived) without HashKey merchant
 * credentials, which require ops-team registration. Every cryptographic
 * operation (JWT signing, HMAC, on-chain write) runs for real against real
 * contracts on HashKey Chain testnet.
 *
 * Replace with Redis / Postgres to survive restarts; single-instance
 * in-memory is fine for demo + single-node deployments.
 */

export interface SandboxCart {
  cartMandateId: string; // ID1
  paymentRequestId: string; // ID2
  flowId: string; // ID3 — generated by the gateway
  merchantName: string;
  appKey: string;
  amountUsd: string;
  usdcMinorUnits: string; // "15000000" for $15
  merchantPayTo: string; // x402 pay_to
  tokenAddress: string;
  chainId: number;
  network: string;
  redirectUrl?: string;
  expiresAt: string; // ISO
  createdAt: string; // ISO
  status:
    | "payment-required"
    | "payment-submitted"
    | "payment-verified"
    | "payment-processing"
    | "payment-successful"
    | "payment-failed";
  payerAddress?: string;
  txSignature?: string;
  completedAt?: string;
  statusReason?: string;
}

// Persist on globalThis so state survives Next.js dev-mode HMR reloads.
declare global {
  // eslint-disable-next-line no-var
  var __zp_hp2_sandbox: {
    byFlow: Map<string, SandboxCart>;
    byCartMandate: Map<string, string>;
    byPaymentRequest: Map<string, string>;
  } | undefined;
}
const state =
  globalThis.__zp_hp2_sandbox ??
  (globalThis.__zp_hp2_sandbox = {
    byFlow: new Map(),
    byCartMandate: new Map(),
    byPaymentRequest: new Map(),
  });
const byFlow = state.byFlow;
const byCartMandate = state.byCartMandate;
const byPaymentRequest = state.byPaymentRequest;

/** Strip ms off ISO and return RFC 3339-compatible "Z" suffix. */
function iso(ms = Date.now()): string {
  return new Date(ms).toISOString().replace(/\.\d{3}Z$/, "Z");
}

export function newFlowId(): string {
  return randomUUID();
}

export function storeCart(cart: SandboxCart): void {
  byFlow.set(cart.flowId, cart);
  byCartMandate.set(cart.cartMandateId, cart.flowId);
  byPaymentRequest.set(cart.paymentRequestId, cart.flowId);
}

export function getCartByFlowId(flowId: string): SandboxCart | undefined {
  return byFlow.get(flowId);
}

export function getCartByCartMandateId(id: string): SandboxCart | undefined {
  const f = byCartMandate.get(id);
  return f ? byFlow.get(f) : undefined;
}

export function getCartByPaymentRequestId(id: string): SandboxCart | undefined {
  const f = byPaymentRequest.get(id);
  return f ? byFlow.get(f) : undefined;
}

export function updateCartStatus(
  flowId: string,
  patch: Partial<Pick<SandboxCart, "status" | "payerAddress" | "txSignature" | "completedAt" | "statusReason">>,
): SandboxCart | undefined {
  const cart = byFlow.get(flowId);
  if (!cart) return undefined;
  Object.assign(cart, patch);
  return cart;
}

export { iso };
